version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: python-dotenv
    versions:
    - 0.15.0
    - 0.16.0
  - dependency-name: autopep8
    versions:
    - 1.5.4
    - 1.5.5
  - dependency-name: pydocstyle
    versions:
    - 5.1.1
  - dependency-name: flask-sqlalchemy
    versions:
    - 2.4.4
  - dependency-name: gunicorn
    versions:
    - 20.0.4
